require = require("esm")(module/*, options*/)
// module.exports = require("./src/index.js");
// module.exports = require("./tests/Routing.test.js");
// module.exports = require("./tests/Subscribe.test.js");
// module.exports = require("./tests/WebSocket.test.js");
// module.exports = require("./tests/Main.test.js");
// module.exports = require("./tests/MSR.test.js");
// module.exports = require("./tests/SCR.test.js");
// module.exports = require("./v3/tests/Channel.test.js");
module.exports = require("./v3/tests/IO.test.js");